### Crear un nuevo Producto
# Enviamos un POST a nuestro endpoint con un cuerpo JSON.
# Fíjate que usamos proveedorId: 1 (el que acabamos de crear).
POST http://localhost:8080/api/productos
Content-Type: application/json

{
  "nombre": "Tornillo de Acero",
  "descripcion": "Tornillo 5mm para madera",
  "precio": 0.15,
  "proveedorId": 1
}

###
###
### --- SECCIÓN DE PROVEEDORES ---
###

### 1. Listar todos los Proveedores (GET)
# Deberíamos ver al menos el "Proveedor de Ferretería" que creamos manualmente antes
# y los nuevos que creemos ahora.
GET http://localhost:8080/api/proveedores

### 2. Crear un nuevo Proveedor (POST)
# Vamos a crear un segundo proveedor vía API.
POST http://localhost:8080/api/proveedores
Content-Type: application/json

{
  "nombre": "Proveedor de Electrónica",
  "importeMinimoPedido": 150.00
}

###
### --- SECCIÓN DE PEDIDOS ---
###

### 1. Listar todos los Pedidos (GET)
# Inicialmente debería devolver una lista vacía [].


### 2. Crear un Pedido Completo (POST)
# Aquí probamos la estructura compleja: Cabecera + Lista de Items.
# Estamos pidiendo: "Soy Josemari y quiero 10 unidades del producto 1".
POST http://localhost:8080/api/pedidos
Content-Type: application/json

{
  "nombreCliente": "Josemari Empresa Saboteador SL",
  "items": [
    {
      "productoId": 9999,
      "cantidad": 10
    }
  ]
}

#########
GET http://localhost:8080/api/pedidos

### Prueba de Regla de Negocio: Pedido que NO llega al mínimo (1.50 < 50.00)
POST http://localhost:8080/api/pedidos
Content-Type: application/json

{
  "nombreCliente": "Cliente Minorista",
  "items": [
    { "productoId": 1, "cantidad": 10 }
  ]
}

### Prueba de Regla de Negocio: Pedido que SÍ supera al mínimo (150.00 > 50.00)
POST http://localhost:8080/api/pedidos
Content-Type: application/json

{
  "nombreCliente": "Gran Empresa SL",
  "items": [
    { "productoId": 1, "cantidad": 1000 }
  ]
}